### ISSUE TITLE
Status of project?

### ISSUE THREAD

**Issue by imjakechapman** [mspae/react-wavesurfer#1]
I'm pretty pumped I found this since I'm converting an application to React and didn't think I'd find a React Component for wavesurfer.

What's the current status of the component? Anything I could possibly do?

**Comment by mspae** [comment]
Hey, I'm glad you find it useful. Obviously there is some demand for the project, so let's improve it!

I think to make this really useful we need two things:
* better docs (which explain how the component can interact with the wavesurfer API)
* find a cool way to include wavesurfer plugins without a) bloating the code for use cases where you don't need the plugins and b) adding npm modules for each plugin (e.g. react-wavesurfer-timeline)

This is my first NPM module, so I'm still figuring things out. But my guess is exporting a react component for each plugin and then adding that as a child to the root component would be a good idea. Then we could have the wavesurfer plugin code required from those submodules (=only if you need it). Like so …

```javascript
import Wavesurfer, {Timeline, Regions} from '../src/react-wavesurfer';

// …
render() {
  <Wavesurfer {...props}>
    <Timeline />
    <Regions />
  </Wavesurfer>
}
```

What do you think? (I will try and get round to updating the docs with a "getting started" guide and a basic primer on how to use tomorrow)

**Comment by mspae** [comment]
Okay I just got round to updating the docs and will now have a go at the wavesurfer plugins implementation. Apart from your comments on that (and all of the codebase, all of which is open for discussion/pull requests of course), filing issues would definitely help since I expect using this component in a realworld project will show up lots of little difficulties which I would probably not notice while developing this component as-is in this sandbox-ish kind of way. Cheers!

**Comment by mspae** [comment]
So I've added better examples (see `examples/index.jsx`) and updated the docs because I've changed the callback props API.

Apparently the wavesurfer.js plugin module format might change in the near future (they're currently discussing this here https://github.com/katspaugh/wavesurfer.js/issues/608) – So I will wait with the other plugins until there is a new release.

**Comment by mleung** [comment]
@mspae Quick question on the timeline plugin, do I have to vendor that somewhere in my project? The example shows: const WaveSurferTimeline = require('wavesurfer.js/plugin/wavesurfer.timeline.js');

So I'm assuming I have to have the regular wavesurfer source, right? Thanks.

**Comment by mspae** [comment]
So wavesurfer.js plugins are now available in UMD format which makes it much easier to include the code. The wrappers for the plugins I mentioned above have now been implemented and seem to be working fine. I think the next step is to tread the wheel of bug fixing and adding tests, improving stability and usability.

**Comment by ffxsam** [comment]
Ok, I'm stumped. How do I include plugins? (I'm using ES6 imports)

**Comment by ffxsam** [comment]
PS: Thank you TONS for porting this to React. You have no idea how helpful this is to me.
