### ISSUE TITLE
accessing all wavesurfer.js Methods

### ISSUE THREAD

**Issue by t22james** [mspae/react-wavesurfer#10]
Hi there,
I'm wondering how I would go about using all of wavesurfer methods from within your port. For example, I'd like to use getDuration(), but am not sure how to access the waveform object?
ref: http://wavesurfer-js.org/docs/methods.html

Also to be able to redraw the waveform as explained here:
https://github.com/katspaugh/wavesurfer.js/issues/131

Thanks :)

**Comment by mspae** [comment]
The wavesurfer instance is passed along with the callback props. You can then either cache that in a variable for reuse or immediately call whatever function you want:
```javascript
// ...
handleReady(args) {
  // call method immediately:
  this.duration = args.wavesurfer.getDuration();
  // … or cache wavesurfer instance:
  this.wavesurferInstance = args.wavesurfer;
},
render() {
  return (
    <Wavesurfer
      onReady={this.handleReady}
    />
  );
```

For the time being you can also use this method to rerender the waveform, however since this is probably quite a common use case I'm considering adding this feature to the component itself.

**Comment by t22james** [comment]
Fantastic! Would be great to add that little nugget/example to the readme :)

**Comment by t22james** [comment]
And yes I think when the scrollable option is turned off, then i think it could likely be assumed that the waveform will be desired as 'responsive'...

**Comment by mspae** [comment]
@t22james As per 0.8.0 the component is responsive by default (can be disabled by passing `false` as `responsive` prop) (see https://github.com/mspae/react-wavesurfer/commit/d7f610bb65d0a65d27e0a41d1a05ee3fa343fe21)
