### ISSUE TITLE
lib doesn't match src?

### ISSUE THREAD

**Issue by ffxsam** [mspae/react-wavesurfer#13]
I noticed some stuff is very different between the two folders, e.g. there's no `enableDragSelection` function in src, but there is in lib.

**Comment by mspae** [comment]
The regions plugin file in `./lib` includes the WaveSurfer.Region plugin which includes the `enableDragSelection` you mention. This is not present in the `./src` version of the file because there the WaveSurfer.Region plugin is only required.

BTW, the wavesurfer.js main file (i.e. what you get when you `require('wavesurfer.js')`) is not included in any build file anymore since I couldn't get it to work with the plugin components and the main wrapper component.

But this should definitely be documented better.

Also I think the `./lib` directory should be removed from source control.
