### ISSUE TITLE
enableDragSelection() method

### ISSUE THREAD

**Issue by n-sakib** [mspae/react-wavesurfer#23]
Hello, I cannot implement enableDragSelection to add new regions, can anyone help me?

**Comment by mspae** [comment]
Hooking into the `ready` event callback is a really great generic way of using the underlying API in a consistent way. In this case the code could look like this.

Keep in mind though that you would probably want to hook up the regions property to some state object and add a callback prop `onRegionUpdated` (wavesurfer.js event `region-updated`) so that the regions you add by using `enableDragSelection` are synced with the `regions` state.

```javascript
import React, { Component } from 'react';
import Wavesurfer from 'react-wavesurfer';
import Regions from 'react-wavesurfer/lib/plugins/regions.js';

export default class App extends Component {
  constructor(props) {
    super(props);

    this.handleReady = this.handleReady.bind(this);
  }
  handleReady({ wavesurfer, originaArgs }) {
    wavesurfer.enableDragSelection({});
  }
  render() {
    return (
      <div>
        <Wavesurfer
          audioFile="https://ia902606.us.archive.org/35/items/shortpoetry_047_librivox/song_cjrg_teasdale_64kb.mp3"
          onReady={this.handleReady}
        >
          <Regions regions={{}} />
        </Wavesurfer>
      </div>
    );
  }
}
```

**Comment by n-sakib** [comment]
Hi, Thank you very much, Can you tell me further how to use onRegionUpdated to keep the sync between new regions and the region object?

**Comment by n-sakib** [comment]
Thank you for the answer, But the latest problem that I am facing is, I can sync the newly created region with the regions state but onSingleUpdate doesn't seem to work on the new regions. Can you tell me how to fix that?
