### ISSUE TITLE
Huge amount of re-renders during playback?

### ISSUE THREAD

**Issue by Jahosh** [mspae/react-wavesurfer#26]
Lately i've been going through my components to try to find which ones are re-rendering unnecessarily. Upon testing a component that had react-wavesurfer in it I found that during playback it re-renders at an extremely high rate. I'm still new to react and i'm wondering if this is a performance issue? Would having 10-20 tracks on a page be extremely inefficient?

![screen shot 2016-11-11 at 7 03 18 pm](https://cloud.githubusercontent.com/assets/15853188/20235255/fedcc65e-a841-11e6-8d01-c816faf866cc.png)

**Comment by mspae** [comment]
`shouldComponentUpdate` always returns true, which means `react-wavesurfer` is never actually rendered to the DOM. (Only once at the beginning – The actually updating happens in `componentWillReceiveProps`) – What happens is that the position prop changes during playback if you use the `onPosChange` callback to set it from within the component. In `componentWillReceiveProps` the component is being *updated* – This does not apply to those cases during playback because the component checks if it is already at that position and then ignores that.
