### ISSUE TITLE
Calling player's api function

### ISSUE THREAD

**Issue by omerts** [mspae/react-wavesurfer#6]
Hello,

How can we call api functions such as setVolume(newVolume)?

**Comment by mspae** [comment]
Thinking inside the React paradigm the correct way would be to pass the volume in as a prop and have the wrapper component call the API function if needed. However, since this is not implemented yet the way to do it currently would be to hook into the `onReady` callback prop (which gets passed the wavesurfer instance) and either set the volume there or cache the instance in a variable and call the `setVolume` method on that.
