### ISSUE TITLE
pos is ignored after initial load

### ISSUE THREAD

**Issue by omerts** [mspae/react-wavesurfer#9]
Changing the pos property after player's initial load is not changing the audio's cursor position.

**Comment by mspae** [comment]
Hi,

Could you check if this is still happening? I updated the dev example to load the initial position in `onReady` but setting it directly as a prop (e.g. `pos={2}`) works with me too.

**Comment by spielc** [comment]
I am able to confirm that this issue still exists. Everything works as expected if i click on the WaveSurfer canvas but if i try to change the value of the pos-property after i have started playback nothing happens. it works though if i change it before i start to actually play something e.g. if i set the pos-property in the onReady-eventhandler

**Comment by mspae** [comment]
This is due to the fact that while playing the position is updated constantly, thus the value of the input field in the example gets updated while you're trying to put in a new value.

I have added a button which fires a function which sets the position to check this and I can confirm it changes the position to the correct value even when playing. (Code is in this branch https://github.com/mspae/react-wavesurfer/tree/pos-check)

Thanks for the comment anyway though :+1:
